site_name: Sua Finança
repo_url: https://github.com/unb-mds/2024-2-SuaFinanca.git
docs_dir: documents
site_dir: site


nav:
  - Sobre: index.md
  - Arquitetura: doc/architecture.md
  - Como contribuir?: doc/contributing.md

  - Documentação:
      - Backend.md: doc/backend.md
      - Documentação Para Padrões de Commit: doc/commit.md
      - Configuração do Ambiente: doc/configAmbiente.md
      - Issues: doc/issues.md
      - Relatório de Avaliação do Framework Next.js: doc/next.md
      - Documentação Básica sobre React.js: doc/react.md
      - Requisitos Funcionais Detalhados: doc/requirements.md


  - Sprints:
    - Sprint 0:  doc/sprints/sprint_0.md
    - Sprint 1:  doc/sprints/sprint_1.md
    - Sprint 2:  doc/sprints/sprint_2.md
    - Sprint 3:  doc/sprints/sprint_3.md
    - Sprint 4:  doc/sprints/sprint_4.md
    - Sprint 5:  doc/sprints/sprint_5.md
    #- Sprint 6: sprints/sprint-11.md
    #- Sprint 7: sprints/sprint-12.md
    #- Sprint 8: sprints/sprint-8.md
    #- Sprint 9: sprints/sprint-9.md
    #- Sprint 10: sprints/sprint-10.md
    #- Sprint 11: sprints/sprint-11.md
    #- Sprint 12: sprints/sprint-12.md
    #- Sprint 13: sprints/sprint-13.md

  - Prototipo: doc/prototype/highFidelity.md
  - Estudos:
      - Como Commitar em Grupo: studies/Resumo-Commit-Grupo.md
      - Resumo de Solid: studies/Resumo-de-SOLID.md
      - Resumo Docker: studies/Resumo-Docker.md
      - Resumo Estudo GIT: studies/Resumo-Estudo-GIT.md
      - Resumo Teste Automatizados: studies/Resumo-Testes-Automatizados.md


theme:
  name: material
  palette:
    # Configuração fixa para fundo preto (modo escuro como padrão)
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    
